{{- $root := . -}}
{{- $list := .Values.ingresses | default (list) -}}
{{- $ic := .Values.ingressClass | default (dict) -}}
{{- $icName := (get $ic "name") | default "" -}}
{{- range $i, $ing := $list }}
{{- if $ing.enabled | default true }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" (include "agent.fullname" $root) (default (printf "ingress-%d" $i) $ing.name) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "agent.labels" $root | nindent 4 }}
spec:
  ingressClassName: {{ default "alb" (coalesce $ing.className $icName) }}
  rules:
    {{- if and $ing.hosts (gt (len $ing.hosts) 0) }}
    {{- range $h := $ing.hosts }}
    - host: {{ $h.host | quote }}
      http:
        paths:
          {{- range $p := $h.paths }}
          - path: {{ $p.path }}
            pathType: {{ default "Prefix" $p.pathType }}
            backend:
              service:
                name: {{ default (include "agent.fullname" $root) ($ing.service.name | default "") }}
                port:
                  {{- if and $ing.service $ing.service.port (hasKey $ing.service.port "number") }}
                  number: {{ $ing.service.port.number }}
                  {{- else }}
                  name: {{ $ing.service.port.name }}
                  {{- end }}
          {{- end }}
    {{- end }}
    {{- else }}
    - http:
        paths:
          {{- $paths := (default (list (dict "path" "/" "pathType" "Prefix")) $ing.paths) }}
          {{- range $p := $paths }}
          - path: {{ $p.path }}
            pathType: {{ default "Prefix" $p.pathType }}
            backend:
              service:
                name: {{ default (include "agent.fullname" $root) ($ing.service.name | default "") }}
                port:
                  {{- if and $ing.service $ing.service.port (hasKey $ing.service.port "number") }}
                  number: {{ $ing.service.port.number }}
                  {{- else }}
                  name: {{ $ing.service.port.name }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}