{{- $ings := .Values.ingresses | default (list) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}
  ports:
    {{- if eq (len $ings) 0 }}
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    {{- else }}
    {{- range $i, $ing := $ings }}
    - name: {{ if and $ing.service $ing.service.port (hasKey $ing.service.port "name") }}{{ $ing.service.port.name }}{{ else }}{{ printf "port-%d" $i }}{{ end }}
      port: {{ if and $ing.service $ing.service.port (hasKey $ing.service.port "number") }}{{ $ing.service.port.number }}{{ else }}{{ add 8000 $i }}{{ end }}
      targetPort: {{ if and $ing.service $ing.service.port (hasKey $ing.service.port "name") }}{{ $ing.service.port.name }}{{ else }}{{ printf "port-%d" $i }}{{ end }}
      protocol: TCP
    {{- end }}
    {{- end }}